os: [linux, osx]

addons:
  apt:
    packages:
      - liblzma-dev
      - ninja-build
      - tree
      - zlib1g-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tree ; fi

script: ./build/travis.sh
